name: alaqsa_visitor_guide
description: A mobile-friendly visitor guide app for Al-Aqsa Mosque.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15  # For storing user preferences
  flutter_native_splash: ^2.2.0  # For splash screen
  cached_network_image: ^3.2.0  # For image caching
  flutter_svg: ^1.0.3  # For SVG support
  flutter_dotenv: ^5.1.0
  http: ^0.13.6
  url_launcher: ^6.1.11	
  booking_calendar: ^1.1.10
  font_awesome_flutter: ^10.7.0 # or latest version
  hijri: ^3.0.0 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2  # For app icons

flutter:
  uses-material-design: true
  
  # Add asset configuration for better mobile experience
  assets:
    - assets/images/
